#!/usr/bin/env julia
#
#===- git-juliafmt - DocumentFormat.jl Git Integration ---------*- julia -*--===#
#
#     Based heavily on ClangFormat's git-clang-format.
#
#===------------------------------------------------------------------------===#

using GitJuliaFormat

GitJuliaFormat.main(ARGS)
